### ISSUE TITLE
Module not working on 2.0.2

### ISSUE THREAD

**Issue by gazjoy** [SchumacherFM/Magento2-Twig#1]
Hi there, thanks for this module but unfortunately I cant get anything working on M2.0.2. I have followed your instructions on installing via composer but nothing is showing in the admin or working when I create a .twig template file.

**Comment by SchumacherFM** [comment]
Ah yes. It is maybe a bit outdated because I've developed it long time before M2 1.0 has been released.

Are you in the mood to send me a pull request and fix this issue?

**Comment by gazjoy** [comment]
I can have a look but can't promise anything :smile:

**Comment by dan-advantec** [comment]
You might be suffering from the twig cache, this can be disabled within the admin area. But it's possible that will also be broken as there is an invalid source model.
I've fixed it in my fork - but I had to also remove the PHP version requirements as that was also causing issues for me.
@SchumacherFM would you mind casting your eye over it before I make a pull request?

**Comment by SchumacherFM** [comment]
Looks good @dan-advantec please merge it yourself as you now have collaborator access.

**Comment by dan-advantec** [comment]
That's great, thanks @SchumacherFM!
A colleague of mine has built an observer which will allow translations within twig files, once I have fully it I'll add it to the repo.
