### ISSUE TITLE
getChildHtml() returns string

### ISSUE THREAD

**Issue by herman-aka-wouter** [SchumacherFM/Magento2-Twig#10]
Hello Im using your plugin. but when i call `{{ getChildHtml() }}` in a twig file it returns the string of that other file, not output it directly as html content. 

how can i solve that?

**Comment by SchumacherFM** [comment]
Sorry, I don't know.

**Comment by herman-aka-wouter** [comment]
i there.

ive doing some research, and it turns out its an twig thing. you should use `{{ getChildHtml()|raw }}`

**Comment by herman-aka-wouter** [comment]
https://github.com/SchumacherFM/Magento2-Twig/pull/11
