### ISSUE TITLE
Debugging not working and some minor issue

### ISSUE THREAD

**Issue by Triloworld** [SchumacherFM/Magento2-Twig#14]
This section:
https://github.com/SchumacherFM/Magento2-Twig/blob/928ee5359ffcf14ed909bc47da44454932beb53a/Framework/View/TemplateEngine/Twig.php#L84

Need additional line:

> $this->twig->addExtension(new \Twig_Extension_Debug());

As is noted in documentation: https://twig.symfony.com/doc/2.x/functions/dump.html

Additional this package on packagist.org:
https://packagist.org/packages/schumacherfm/magento-twig
is old version and not updating correct.
This https://packagist.org/about on section "GitHub Hook" provide solution to automate stuff once and for all. 

We found some limitation:
vendor/magento/module-theme/view/frontend/templates/html/header/logo.phtml
Line 15:
> $block->isHomePage()

Not working ;( 
We use right now that solution (maybe is correct but not exact as no rewrite occur):
> {% set isHomePage = 'cms/index/index' in getUrl('*/*/*')  %}

Thank you for help :)
PS. We trying to have better template on one of our project to easily maintenance stuff as Magento Developers not so easy to find.

**Comment by Triloworld** [comment]
Pull Request to fix debugging #15

**Comment by SchumacherFM** [comment]
Merged! Thanks! and tagged as 1.1.5
