### ISSUE TITLE
Variable "block" does not exist.

### ISSUE THREAD

**Issue by mnjongerius** [SchumacherFM/Magento2-Twig#18]
I replaced the `list.phtml` template with my own using:
```
<referenceBlock name="category.products.list"  template="Magento_Catalog::product/list-container.twig" />` in `catalog_category_view.xml
```

This works, until I try calling any functions like 
```
{% set products = block.getLoadedProductCollection() %}
```
which gives the Critical error `Variable "block" does not exist.`. 

I was under the impression that using `block.` functions was possible, can you explain me why this isn't working?

**Comment by mnjongerius** [comment]
Turns out I needed to do 
```
{% set products = getLoadedProductCollection() %}
```

Omitting the `block` variable entirely solved my problems

**Comment by SchumacherFM** [comment]
thanks for resolving the issue yourself :-)
