### ISSUE TITLE
Add note about co-working with existing .phtml templates

### ISSUE THREAD

**Issue by Triloworld** [SchumacherFM/Magento2-Twig#3]
If somebody wan't to use this module then:
- I need to know if it **simultaneously** with phtml or need to rewrite phtml files? 
One template is in twig and another is in phtml and run ok?

> "This template engine is meant to be used additionally to the .phtml files and does not provide any .twig template file."

This don't explain if main template is broken or not because it tell only that no twig template is added and the most important - 'used additionally with phtml' - what you mean is additionally==simultaneously?

- I need to know if there exist somewhere default template written in twig files. It will be great. If not, I will work on that so it help me and other. The whole point is to start from twig templates after installing module. Main reason - work together on only one project for default template in twig syntax

This two points can be added to docs or be explained so people won't ask and have clear picture what they get with this module.
Thanks for starting this project. It will help a lot ;)

**Comment by SchumacherFM** [comment]
Thanks for opening this issue!

1. You can use both `.phtml` and `.twig` extension. No need to rewrite `.phtml` into `.twig`. For example you can write all your new template files in twig
2. yes simultaneously is correct
3. No one yet startet this project to port phtml to twig

I hope I could clarified your questions.
