### ISSUE TITLE
Update platform requirments for PHP 7.1 & PHP 7.2

### ISSUE THREAD

**Issue by nedt** [SchumacherFM/Magento2-Twig#4]
composer.json lists ~7.0.11 as requirement. Is this on purpose? We've installed on PHP 7.1 with `--ignore-platform-reqs` and no problems so far. As active development on PHP 7.0 stopped I guess `~5.6.0|>=7.0.11` or `~5.6.0|~7.0.11|~7.1` would be better.

**Comment by SchumacherFM** [comment]
If you can send me a Pull Request with the change, I'm happy to merge it!

**Comment by herman-aka-wouter** [comment]
https://github.com/SchumacherFM/Magento2-Twig/pull/11

**Comment by SchumacherFM** [comment]
Fixed with PR #11
