### ISSUE TITLE
php 7.1

### ISSUE THREAD

**Issue by clemblanco** [SchumacherFM/Magento2-Twig#5]
First question, how come I can't see the dependancy of the official Twig package `"twig/twig:^2.0"` in your `composer.json`?

Second one, why only supporting php 7.0 max?

**Comment by SchumacherFM** [comment]
Hey,

1. Send me a Pull Request and I'm happy to merge it.
2. Send me a Pull Request and I'm happy to merge it.

**Comment by SchumacherFM** [comment]
Fixed via PR #6
