### ISSUE TITLE
\Twig_Autoloader::register() not needed for Twig 2.0 and up

### ISSUE THREAD

**Issue by jaycroll** [SchumacherFM/Magento2-Twig#7]
I've read the documentation that Twig 2.0 and up does not need to call the Twig_Autoloader anymore. Seeing that this module now requires Twig 2.0 and up, i belive it's safe to remove the autoloader in Twig,php

https://github.com/SchumacherFM/Magento2-Twig/blob/fc4752758102f3012dc257d31dd695756c799be0/Framework/View/TemplateEngine/Twig.php#L68

**Comment by SchumacherFM** [comment]
Thanks for reporting. Can you please send a pull request for this update?

**Comment by SchumacherFM** [comment]
Thank you. I've merged the PR #8
