### ISSUE TITLE
Library not found in composer package list

### ISSUE THREAD

**Issue by jaycroll** [SchumacherFM/Magento2-Twig#9]
Can't seem to pull the library from composer. Also checked packagist.org if does exist there. 

![image](https://user-images.githubusercontent.com/1792445/41010363-e8e474ee-6971-11e8-985e-cc91b3d214a0.png)

![image](https://user-images.githubusercontent.com/1792445/41010403-26471c4c-6972-11e8-90c5-a6d92342a4b7.png)

**Comment by SchumacherFM** [comment]
There you go! 
https://packagist.org/packages/schumacherfm/magento-twig
Just added it!
